general {
    disable_loading_bar = false
    hide_cursor = true
    grace = 3
    no_fade_in = false
}

background {
    monitor =
    path = ~/Pictures/Wallpapers/desert-night-sky-3840x2160-15488.jpg
    blur_passes = 3
    blur_size = 7
    brightness = 0.5
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgba(cba6f7ff)
    inner_color = rgba(1e1e2eff)
    font_color = rgba(cdd6f4ff)
    fade_on_empty = true
    placeholder_text = <i>Password</i>
    hide_input = false
    rounding = 10
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgba(cdd6f4ff)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(a6adc8ff)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 130
    halign = center
    valign = center
}
