placeholder = "Search..."

[[modules]]
name = "applications"
prefix = ""
weight = 1

[[modules]]
name = "runner"
prefix = "!"
weight = 10

[[modules]]
name = "websearch"
prefix = "?"
weight = 5

[[modules]]
name = "clipboard"
prefix = "c:"
weight = 2
